### ISSUE TITLE
运行时间

### ISSUE THREAD

**Issue by ZhiyingDu** [leoweyr/2022MatherCup-D#2]
请问一下，代码大概要运行多长时间？

**Comment by leoweyr** [comment]
很慢，因为没有经过多线程优化。实际运行时间没留意过，不过肯定大于十几分钟
https://github.com/leoweyr/2022MathorCup-D/blob/f293c035d1e74e063231971e3245a8a697cc9a2d/README.md?plain=1#L248-L250
https://github.com/leoweyr/2022MathorCup-D/blob/f293c035d1e74e063231971e3245a8a697cc9a2d/README.md?plain=1#L350
